<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <InvariantGlobalization>true</InvariantGlobalization>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <ServerGarbageCollection>true</ServerGarbageCollection>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Keymaker.Infra\Keymaker.Infra.csproj" />
      <ProjectReference Include="..\Keymaker.Service\Keymaker.Service.csproj" />
    </ItemGroup>

</Project>
